lockPref("app.shield.optoutstudies.enabled", false);
lockPref("browser.aboutConfig.showWarning", false);
lockPref("browser.aboutwelcome.enabled", false);
lockPref("browser.bookmarks.restore_default_bookmarks", false);
lockPref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
lockPref("browser.formfill.enable", false);
lockPref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
lockPref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
lockPref("browser.newtabpage.activity-stream.feeds.snippets", false);
lockPref("browser.newtabpage.activity-stream.feeds.topsites", false);
lockPref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
lockPref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
lockPref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
lockPref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);
lockPref("browser.newtabpage.activity-stream.showSearch", true);
lockPref("browser.newtabpage.activity-stream.showSponsored", false);
lockPref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
lockPref("browser.tabs.loadInBackground", false);
lockPref("browser.toolbars.bookmarks.visibility", "always");
lockPref("datareporting.healthreport.uploadEnabled", false);
lockPref("datareporting.policy.firstRunURL", "");
lockPref("dom.disable_open_during_load", true);
lockPref("dom.security.https_only_mode", true);
lockPref("extensions.formautofill.addresses.enabled", false);
lockPref("extensions.formautofill.creditCards.enabled", false);
lockPref("media.eme.enabled", true);
lockPref("network.cookie.lifetimePolicy", 2);
lockPref("places.history.enabled", false);
lockPref("privacy.donottrackheader.enabled", true);
lockPref("privacy.history.custom", true);
lockPref("signon.autofillForms", false);
lockPref("signon.generation.enabled", false);
lockPref("signon.management.page.breach-alerts.enabled", false);
lockPref("signon.rememberSignons", false);
lockPref("xpinstall.whitelist.required", true);

pref("font.minimum-size.x-western", 16);
pref("font.name.monospace.x-western", "Iosevka");
pref("font.size.monospace.x-western", 16);
pref("privacy.clearOnShutdown.offlineApps", true);
pref("privacy.clearOnShutdown.siteSettings", true);
pref("privacy.cpd.cache", true)
pref("privacy.cpd.cookies", true)
pref("privacy.cpd.formdata", true)
pref("privacy.cpd.history", true)
pref("privacy.cpd.offlineApps", true)
pref("privacy.cpd.sessions", true)
pref("privacy.cpd.siteSettings", true)
pref("privacy.sanitize.pending", '[{"id":"shutdown","itemsToClear":["cache","cookies","downloads","formdata","history","offlineApps","sessions","siteSettings"],"options":{}}]');
pref("privacy.sanitize.sanitizeOnShutdown", true);
pref("privacy.sanitize.timeSpan", 0)
